### PR TITLE
Add version catalog for dependency management

### PR DESCRIPTION
**Pull request by jsoberg**
Implemented gradle version catalogs for easier/safer dependency usage.

I also added `local.properties` to the `.gitignore` for those who use Android Studio.

Ran tests for verification, all 9 passed.

### CODE REVIEW

**Comment by JavierSegoviaCordoba** [comment]
I think Version Catalogs should be used instead of buildSrc approach which is not cache friendly.

**Comment by jsoberg** [comment]
I could add that in instead of this, however I don't think we could reference the Kotlin version from TOML when we set the 'kotlin("jvm")' plugin

**Comment by JavierSegoviaCordoba** [comment]
Version catalog supports plugin aliases too

**Comment by jsoberg** [comment]
> Version catalog supports plugin aliases too

True I forgot about that option, I'd be happy to move this over to version catalogs if that's best. I wasn't aware that using `buildSrc` wasn't cache-friendly

**Comment by jsoberg** [comment]
Merged in main and resolved conflicts, I just needed to update to 1.6.10 in the version catalog to mirror that update.

**Comment by jsoberg** [comment]
Let me know if you'd like to add this functionality and I'll open up another PR

**Comment by shanshin** [comment]
Hi, thanks for the contribution.
I propose to implement this feature when it is stabilized in Grade (it won't be a preview) and there will be full support in the IDE.

**Comment by shanshin** [comment]
@JavierSegoviaCordoba, does version `7.4` still require a `enableFeaturePreview("VERSION_CATALOGS")` call?

**Comment by JavierSegoviaCordoba** [comment]
@shanshin no, it can be removed

**Pull request closed without merging**
