### PR TITLE
Added property to exclude Android classes from the instrumentation

### LINKED ISSUE #89: Kover breaks Robolectric
Tested on Kover 0.4.4:
```
plugins {
    id 'org.jetbrains.kotlinx.kover' version '0.4.4'
}
```

Dependencies:
```
testImplementation "org.robolectric:robolectric:4.7.3"
```

Test
```
@RunWith(RobolectricTestRunner::class)
class RobolectricTest {
    @Test
    fun emptyTest() {
        "".toString()
    }
}
```

When I run this, I get this exception:
```
java.lang.IllegalAccessException: class org.robolectric.res.ResourceTableFactory cannot access a member of class android.R$styleable with modifiers "private static transient"
java.lang.RuntimeException: java.lang.IllegalAccessException: class org.robolectric.res.ResourceTableFactory cannot access a member of class android.R$styleable with modifiers "private static transient"
	at org.robolectric.res.ResourceTableFactory.addMissingStyleableAttributes(ResourceTableFactory.java:100)
	at org.robolectric.res.ResourceTableFactory.lambda$newFrameworkResourceTable$0(ResourceTableFactory.java:20)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.res.ResourceTableFactory.newFrameworkResourceTable(ResourceTableFactory.java:13)
	at org.robolectric.android.internal.AndroidTestEnvironment.getSystemResourceTable(AndroidTestEnvironment.java:394)
	at org.robolectric.android.internal.AndroidTestEnvironment.injectResourceStuffForLegacy(AndroidTestEnvironment.java:419)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage_measured(AndroidTestEnvironment.java:365)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$loadAppPackage$3(AndroidTestEnvironment.java:358)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage(AndroidTestEnvironment.java:358)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:257)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$0(AndroidTestEnvironment.java:229)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$1(AndroidTestEnvironment.java:226)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at org.robolectric.RuntimeEnvironment.getApplication(RuntimeEnvironment.java:71)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:194)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:325)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:265)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalAccessException: class org.robolectric.res.ResourceTableFactory cannot access a member of class android.R$styleable with modifiers "private static transient"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1075)
	at java.base/java.lang.reflect.Field.get(Field.java:416)
	at org.robolectric.res.ResourceTableFactory.addMissingStyleableAttributes(ResourceTableFactory.java:98)
```

When I run it without the kover plugin, it succeeds just fine.

### PR DESCRIPTION
**Pull request by shanshin**
Fixes #89

### CODE REVIEW

**Review by qwwdfsad — APPROVED** [review]

**Comment by qwwdfsad** [comment]
The test would be nice to have though. You can even put a classfile from the reproducer to be sure the test fails with VerifyError if something goes wrong

**Review by qwwdfsad — COMMENTED** [review]
Please add a test with Robolectric that does not require Android plugin

**Comment by shanshin** [comment]
> Please add a test with Robolectric that does not require Android plugin

Robolectric uses classes from android.jar so I think these tests can be added only after implementing support of Android tests.

**Comment by qwwdfsad** [comment]
@shanshin it's enough to add stub android JAR.

You can use https://github.com/Kotlin/kotlinx.coroutines/tree/master/ui/kotlinx-coroutines-android as an example of it

**Comment by shanshin** [comment]
> @shanshin it's enough to add stub android JAR.
> 
> You can use https://github.com/Kotlin/kotlinx.coroutines/tree/master/ui/kotlinx-coroutines-android as an example of it, we have some robolectric tests without actual dependency to ART runtime

**Comment by shanshin** [comment]
> @shanshin it's enough to add stub android JAR.
> 
> You can use https://github.com/Kotlin/kotlinx.coroutines/tree/master/ui/kotlinx-coroutines-android as an example of it, we have some robolectric tests without actual dependency to ART runtime

The code checks that the android plugin has been applied, so the test can be written later when the test infrastructure for Android projects is ready.

**Pull request merged**
